apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    NodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Values.name }}